### ISSUE TITLE
Allow other password authenticator to work

### ISSUE THREAD

**Issue by weideng1** [datastax/zdm-proxy#100]
The [current code](https://github.com/datastax/zdm-proxy/blob/f893984498547d5181c0216e955e01949ff5b88b/proxy/pkg/zdmproxy/auth.go#L98-L106) only accepts `com.datastax.bdp.cassandra.auth.DseAuthenticator` and `org.apache.cassandra.auth.PasswordAuthenticator`, which unnecessarily limits the kind of CQL data stores that can be used as `Origin` or `Target`. The proposed change takes [the same approach that CQL python driver takes](https://github.com/datastax/python-driver/blob/master/cassandra/auth.py#L259-L263), i.e. if it's not a DSEAuthenticator, it will assume the CQL data store uses a compatible password authenticator. When we need to handle more non-password authenticators, this segment will likely change back to switch statement, but that's going to be a bigger change any way.

┆Issue is synchronized with this [Jira Task](https://datastax.jira.com/browse/ZDM-530) by [Unito](https://www.unito.io)
┆Components: Proxy
┆Issue Number: ZDM-530

**Comment by ims-swilkinson** [comment]
We've hit this problem trying to migrate from DSE to Astra. For Astra it needs to support the "org.apache.cassandra.auth.AstraAuthenticator" authenticator. This seems to be compatible with "org.apache.cassandra.auth.PasswordAuthenticator" which is already supported.

**Comment by joao-r-reis** [comment]
> We've hit this problem trying to migrate from DSE to Astra. For Astra it needs to support the "org.apache.cassandra.auth.AstraAuthenticator" authenticator. This seems to be compatible with "org.apache.cassandra.auth.PasswordAuthenticator" which is already supported.

the PR hasn't been merged yet but the fix is available in docker image `datastax/zdm-proxy:sha-33db4fd` if needed
