### ISSUE TITLE
Unable to connect via cqlsh to ZDM Proxy - Protocol error

### ISSUE THREAD

**Issue by jporcelg** [datastax/zdm-proxy#111]
I have deployed ZDM Proxy with the purpose of using it against two different Cassandra clusters:

- The first one is Cassandra 2 as _origin_ `[cqlsh 5.0.1 | Cassandra 2.1.21 | CQL spec 3.2.1 | Native protocol v3]` which is in use.
- The second one is Cassandra 4 as _target_ `[cqlsh 6.1.0 | Cassandra 4.1.3 | CQL spec 3.4.6 | Native protocol v5]` empty, at the moment.

Documentation says ZDM Proxy should be compatible with both versions including protocol v5, I am not using any particular v5 functionality either. Unfortunately, I am unable to connect to the proxy using `cqlsh` on port 14002, even downloading the latest client online nor using python code directly.

See the circular error below:

```
# cqlsh $ZDMPROXY 14002 --cqlversion=3.2.1
Connection error: ('Unable to connect to any servers', {'xx.x.x.xx': ProtocolError("cql_version '3.2.1' is not supported by remote (w/ native protocol). Supported versions: [u'3.4.6']",)})
# cqlsh $ZDMPROXY 14002 --cqlversion=3.4.6
Connection error: ('Unable to connect to any servers', {'xx.x.xx.xx': <ErrorMessage code=000a [Protocol error] message="Provided version 3.4.6 is not supported by this server (supported: 2.0.0, 3.2.1)">})
```

I have tried to circumvent that issue without success, which means either I am doing something wrong or I misunderstood the requirements for this setup to work. 

What am I missing?

┆Issue is synchronized with this [Jira Task](https://datastax.jira.com/browse/ZDM-605) by [Unito](https://www.unito.io)
┆Components: Proxy
┆Issue Number: ZDM-605

**Comment by joao-r-reis** [comment]
Because there's not a `cql_version` that is supported by both clusters I don't think that you will be able to get cqlsh to work with zdm there. @absurdfarce correct me if I'm wrong.

You should still be able to connect your application though.

**Comment by absurdfarce** [comment]
Yes, I believe you're correct @joao-r-reis .  I _swear_ we had something like this issue come up before but I cannot for the life of me find a reference to it... maybe I just made it up.
